# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/qt_camera_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1115)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(\"C:/Users/ayberk/Desktop/icons/background.png\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-attachment: fixed;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.sidebarFrame = QtWidgets.QFrame(self.centralwidget)
        self.sidebarFrame.setGeometry(QtCore.QRect(0, 0, 392, 1080))
        self.sidebarFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.sidebarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebarFrame.setObjectName("sidebarFrame")
        self.labelSmart = QtWidgets.QLabel(self.sidebarFrame)
        self.labelSmart.setGeometry(QtCore.QRect(31, 32, 330, 73))
        self.labelSmart.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-size: 58px;\n"
"    font-family: \'Plus Jakarta Sans\';\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.labelSmart.setObjectName("labelSmart")
        self.labelSaw = QtWidgets.QLabel(self.sidebarFrame)
        self.labelSaw.setGeometry(QtCore.QRect(230, 32, 150, 73))
        self.labelSaw.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-size: 58px;\n"
"    font-family: \'Plus Jakarta Sans\';\n"
"    font-weight: 100\n"
";\n"
"}\n"
"")
        self.labelSaw.setObjectName("labelSaw")
        self.lineSmartSaw = QtWidgets.QFrame(self.sidebarFrame)
        self.lineSmartSaw.setGeometry(QtCore.QRect(30, 110, 332, 3))
        self.lineSmartSaw.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgba(255, 255, 255, 0),\n"
"        stop: 0.5 rgba(255, 255, 255, 100),\n"
"        stop: 1 rgba(255, 255, 255, 0)\n"
"    );\n"
"    border: none;\n"
"}\n"
"")
        self.lineSmartSaw.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lineSmartSaw.setLineWidth(1)
        self.lineSmartSaw.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineSmartSaw.setObjectName("lineSmartSaw")
        self.btnControlPanel = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnControlPanel.setGeometry(QtCore.QRect(26, 165, 355, 110))
        font = QtGui.QFont()
        font.setFamily("Plus Jakarta Sans")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.btnControlPanel.setFont(font)
        self.btnControlPanel.setMouseTracking(False)
        self.btnControlPanel.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus Jakarta Sans\';\n"
"    font-weight: semibold;\n"
"    font-size: 32px;\n"
"    text-align: left;\n"
"    padding: 12px 10px 12px 25px;  /* simge için boşluk */\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgba(26, 31, 55, 128); /* %50 opaklık */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/gui\\../../../../../icons/control-panel-icon2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("src/gui\\../../../../../icons/control-panel-icon2-active.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btnControlPanel.setIcon(icon)
        self.btnControlPanel.setIconSize(QtCore.QSize(70, 70))
        self.btnControlPanel.setObjectName("btnControlPanel")
        self.btnPositioning = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnPositioning.setGeometry(QtCore.QRect(26, 286, 355, 110))
        self.btnPositioning.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus Jakarta Sans\';\n"
"    font-weight: semibold;\n"
"    font-size: 32px;\n"
"    text-align: left;\n"
"    padding: 12px 10px 12px 20px;  /* simge için boşluk */\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgba(26, 31, 55, 128); /* %50 opaklık */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/gui\\../../../../../icons/positioning-icon2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("src/gui\\../../../../../icons/positioning-icon2-active.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btnPositioning.setIcon(icon1)
        self.btnPositioning.setIconSize(QtCore.QSize(80, 80))
        self.btnPositioning.setObjectName("btnPositioning")
        self.btnCamera = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnCamera.setGeometry(QtCore.QRect(26, 407, 355, 110))
        self.btnCamera.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus Jakarta Sans\';\n"
"    font-weight: semibold;\n"
"    font-size: 32px;\n"
"    text-align: left;\n"
"    padding: 12px 10px 12px 20px;  /* simge için boşluk */\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgba(26, 31, 55, 128); /* %50 opaklık */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("src/gui\\../../../../../icons/camera-icon2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("src/gui\\../../../../../icons/camera-icon-active.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btnCamera.setIcon(icon2)
        self.btnCamera.setIconSize(QtCore.QSize(80, 80))
        self.btnCamera.setObjectName("btnCamera")
        self.btnSensor = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnSensor.setGeometry(QtCore.QRect(26, 528, 355, 110))
        self.btnSensor.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus Jakarta Sans\';\n"
"    font-weight: semibold;\n"
"    font-size: 32px;\n"
"    text-align: left;\n"
"    padding: 12px 10px 12px 20px;  /* simge için boşluk */\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgba(26, 31, 55, 128); /* %50 opaklık */\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("src/gui\\../../../../../icons/sensor-icon2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("src/gui\\../../../../../icons/sensor-icon2-active.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btnSensor.setIcon(icon3)
        self.btnSensor.setIconSize(QtCore.QSize(80, 80))
        self.btnSensor.setObjectName("btnSensor")
        self.btnTracking = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnTracking.setGeometry(QtCore.QRect(27, 649, 355, 110))
        self.btnTracking.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus Jakarta Sans\';\n"
"    font-weight: semibold;\n"
"    font-size: 32px;\n"
"    text-align: left;\n"
"    padding: 12px 10px 12px 20px;  /* simge için boşluk */\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgba(26, 31, 55, 128); /* %50 opaklık */\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("src/gui\\../../../../../icons/tracking-icon2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("src/gui\\../../../../../icons/tracking-icon2-active.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btnTracking.setIcon(icon4)
        self.btnTracking.setIconSize(QtCore.QSize(80, 80))
        self.btnTracking.setObjectName("btnTracking")
        self.notificationFrame = QtWidgets.QFrame(self.centralwidget)
        self.notificationFrame.setGeometry(QtCore.QRect(425, 38, 1465, 60))
        self.notificationFrame.setStyleSheet("QFrame#notificationFrame {\n"
"    background-color: rgba(26, 31, 55, 77);\n"
"    border-radius: 30px;\n"
"}")
        self.notificationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notificationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notificationFrame.setObjectName("notificationFrame")
        self.labelDate = QtWidgets.QLabel(self.notificationFrame)
        self.labelDate.setGeometry(QtCore.QRect(55, 13, 300, 34))
        self.labelDate.setStyleSheet("QLabel {\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus Jakarta Sans\';\n"
"    font-size: 24px;\n"
"    font-weight: light;\n"
"}\n"
"")
        self.labelDate.setObjectName("labelDate")
        self.labelTime = QtWidgets.QLabel(self.notificationFrame)
        self.labelTime.setGeometry(QtCore.QRect(1348, 13, 62, 34))
        self.labelTime.setStyleSheet("QLabel {\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus Jakarta Sans\';\n"
"    font-size: 24px;\n"
"    font-weight: light;\n"
"}\n"
"")
        self.labelTime.setObjectName("labelTime")
        self.KameraFrame = QtWidgets.QFrame(self.centralwidget)
        self.KameraFrame.setGeometry(QtCore.QRect(425, 125, 934, 525))
        self.KameraFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.KameraFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.KameraFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.KameraFrame.setObjectName("KameraFrame")
        self.TespitEdilenKirikFrame = QtWidgets.QFrame(self.KameraFrame)
        self.TespitEdilenKirikFrame.setGeometry(QtCore.QRect(515, 400, 260, 105))
        self.TespitEdilenKirikFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.TespitEdilenKirikFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TespitEdilenKirikFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TespitEdilenKirikFrame.setObjectName("TespitEdilenKirikFrame")
        self.labelTespitEdilenKirik = QtWidgets.QLabel(self.TespitEdilenKirikFrame)
        self.labelTespitEdilenKirik.setGeometry(QtCore.QRect(24, 20, 221, 20))
        self.labelTespitEdilenKirik.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color:    #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: medium;\n"
"    font-size: 20px;\n"
"}")
        self.labelTespitEdilenKirik.setObjectName("labelTespitEdilenKirik")
        self.labelTespitEdilenKirikValue = QtWidgets.QLabel(self.TespitEdilenKirikFrame)
        self.labelTespitEdilenKirikValue.setGeometry(QtCore.QRect(91, 43, 151, 50))
        font = QtGui.QFont()
        font.setFamily("Plus-Jakarta-Sans")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelTespitEdilenKirikValue.setFont(font)
        self.labelTespitEdilenKirikValue.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: bold;\n"
"    font-size: 36px;\n"
"}")
        self.labelTespitEdilenKirikValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTespitEdilenKirikValue.setObjectName("labelTespitEdilenKirikValue")
        self.TespitEdilenDisFrame = QtWidgets.QFrame(self.KameraFrame)
        self.TespitEdilenDisFrame.setGeometry(QtCore.QRect(158, 400, 260, 105))
        self.TespitEdilenDisFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.TespitEdilenDisFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TespitEdilenDisFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TespitEdilenDisFrame.setObjectName("TespitEdilenDisFrame")
        self.labelTespitEdilenDis = QtWidgets.QLabel(self.TespitEdilenDisFrame)
        self.labelTespitEdilenDis.setGeometry(QtCore.QRect(24, 20, 211, 20))
        self.labelTespitEdilenDis.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color:    #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: medium;\n"
"    font-size: 20px;\n"
"}")
        self.labelTespitEdilenDis.setObjectName("labelTespitEdilenDis")
        self.labelTespitEdilenDisValue = QtWidgets.QLabel(self.TespitEdilenDisFrame)
        self.labelTespitEdilenDisValue.setGeometry(QtCore.QRect(91, 43, 151, 50))
        font = QtGui.QFont()
        font.setFamily("Plus-Jakarta-Sans")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelTespitEdilenDisValue.setFont(font)
        self.labelTespitEdilenDisValue.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: bold;\n"
"    font-size: 36px;\n"
"}")
        self.labelTespitEdilenDisValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTespitEdilenDisValue.setObjectName("labelTespitEdilenDisValue")
        self.TestereSagligiFrame = QtWidgets.QFrame(self.centralwidget)
        self.TestereSagligiFrame.setGeometry(QtCore.QRect(762, 961, 260, 105))
        self.TestereSagligiFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.TestereSagligiFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TestereSagligiFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TestereSagligiFrame.setObjectName("TestereSagligiFrame")
        self.labelTestereSagligi = QtWidgets.QLabel(self.TestereSagligiFrame)
        self.labelTestereSagligi.setGeometry(QtCore.QRect(33, 20, 221, 20))
        self.labelTestereSagligi.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color:    #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: medium;\n"
"    font-size: 20px;\n"
"}")
        self.labelTestereSagligi.setObjectName("labelTestereSagligi")
        self.labelTestereSagligiValue = QtWidgets.QLabel(self.TestereSagligiFrame)
        self.labelTestereSagligiValue.setGeometry(QtCore.QRect(11, 43, 231, 50))
        font = QtGui.QFont()
        font.setFamily("Plus-Jakarta-Sans")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelTestereSagligiValue.setFont(font)
        self.labelTestereSagligiValue.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: bold;\n"
"    font-size: 36px;\n"
"}")
        self.labelTestereSagligiValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTestereSagligiValue.setObjectName("labelTestereSagligiValue")
        self.AsinmaYuzdesiFrame = QtWidgets.QFrame(self.centralwidget)
        self.AsinmaYuzdesiFrame.setGeometry(QtCore.QRect(425, 961, 260, 105))
        self.AsinmaYuzdesiFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.AsinmaYuzdesiFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AsinmaYuzdesiFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AsinmaYuzdesiFrame.setObjectName("AsinmaYuzdesiFrame")
        self.labelAsinmaYuzdesi = QtWidgets.QLabel(self.AsinmaYuzdesiFrame)
        self.labelAsinmaYuzdesi.setGeometry(QtCore.QRect(33, 20, 201, 31))
        self.labelAsinmaYuzdesi.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color:    #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: medium;\n"
"    font-size: 20px;\n"
"}")
        self.labelAsinmaYuzdesi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelAsinmaYuzdesi.setObjectName("labelAsinmaYuzdesi")
        self.labelAsinmaYuzdesiValue = QtWidgets.QLabel(self.AsinmaYuzdesiFrame)
        self.labelAsinmaYuzdesiValue.setGeometry(QtCore.QRect(11, 43, 231, 50))
        font = QtGui.QFont()
        font.setFamily("Plus-Jakarta-Sans")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelAsinmaYuzdesiValue.setFont(font)
        self.labelAsinmaYuzdesiValue.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: bold;\n"
"    font-size: 36px;\n"
"}")
        self.labelAsinmaYuzdesiValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAsinmaYuzdesiValue.setObjectName("labelAsinmaYuzdesiValue")
        self.TestereDurumuFrame = QtWidgets.QFrame(self.centralwidget)
        self.TestereDurumuFrame.setGeometry(QtCore.QRect(1099, 961, 260, 105))
        self.TestereDurumuFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.TestereDurumuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TestereDurumuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TestereDurumuFrame.setObjectName("TestereDurumuFrame")
        self.labelTestereDurumu = QtWidgets.QLabel(self.TestereDurumuFrame)
        self.labelTestereDurumu.setGeometry(QtCore.QRect(33, 20, 221, 20))
        self.labelTestereDurumu.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color:    #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: medium;\n"
"    font-size: 20px;\n"
"}")
        self.labelTestereDurumu.setObjectName("labelTestereDurumu")
        self.labelTestereDurumuValue = QtWidgets.QLabel(self.TestereDurumuFrame)
        self.labelTestereDurumuValue.setGeometry(QtCore.QRect(11, 43, 231, 50))
        font = QtGui.QFont()
        font.setFamily("Plus-Jakarta-Sans")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelTestereDurumuValue.setFont(font)
        self.labelTestereDurumuValue.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: bold;\n"
"    font-size: 36px;\n"
"}")
        self.labelTestereDurumuValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTestereDurumuValue.setObjectName("labelTestereDurumuValue")
        self.SiraliGoruntuFrame = QtWidgets.QFrame(self.centralwidget)
        self.SiraliGoruntuFrame.setGeometry(QtCore.QRect(427, 687, 934, 150))
        self.SiraliGoruntuFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.SiraliGoruntuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SiraliGoruntuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SiraliGoruntuFrame.setObjectName("SiraliGoruntuFrame")
        self.TestereDegisimFrame = QtWidgets.QFrame(self.centralwidget)
        self.TestereDegisimFrame.setGeometry(QtCore.QRect(425, 873, 934, 60))
        self.TestereDegisimFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.TestereDegisimFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TestereDegisimFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TestereDegisimFrame.setObjectName("TestereDegisimFrame")
        self.labelTestereDegisim = QtWidgets.QLabel(self.TestereDegisimFrame)
        self.labelTestereDegisim.setGeometry(QtCore.QRect(35, 19, 365, 25))
        self.labelTestereDegisim.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color:    #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: medium;\n"
"    font-size: 22px;\n"
"}")
        self.labelTestereDegisim.setObjectName("labelTestereDegisim")
        self.labelTestereDegisimTarih = QtWidgets.QLabel(self.TestereDegisimFrame)
        self.labelTestereDegisimTarih.setGeometry(QtCore.QRect(675, 16, 226, 28))
        self.labelTestereDegisimTarih.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelTestereDegisimTarih.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color:    #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: medium;\n"
"    font-size: 28px;\n"
"}")
        self.labelTestereDegisimTarih.setText("77.77.7777")
        self.labelTestereDegisimTarih.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTestereDegisimTarih.setObjectName("labelTestereDegisimTarih")
        self.KirikTespitiFrame = QtWidgets.QFrame(self.centralwidget)
        self.KirikTespitiFrame.setGeometry(QtCore.QRect(1385, 125, 505, 438))
        self.KirikTespitiFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.KirikTespitiFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.KirikTespitiFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.KirikTespitiFrame.setObjectName("KirikTespitiFrame")
        self.labelKirikTespiti = QtWidgets.QLabel(self.KirikTespitiFrame)
        self.labelKirikTespiti.setGeometry(QtCore.QRect(34, 19, 461, 45))
        font = QtGui.QFont()
        font.setFamily("Plus-Jakarta-Sans")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelKirikTespiti.setFont(font)
        self.labelKirikTespiti.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: bold;\n"
"    font-size: 32px;\n"
"}")
        self.labelKirikTespiti.setObjectName("labelKirikTespiti")
        self.KirikTespitiInfoFrame = QtWidgets.QFrame(self.KirikTespitiFrame)
        self.KirikTespitiInfoFrame.setGeometry(QtCore.QRect(31, 94, 443, 60))
        self.KirikTespitiInfoFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, \n"
"    x2:1, y2:1, \n"
"    stop:0 rgba(0, 0, 0, 255), \n"
"    stop:1 rgba(124, 4, 66, 255)\n"
");\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.KirikTespitiInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.KirikTespitiInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.KirikTespitiInfoFrame.setObjectName("KirikTespitiInfoFrame")
        self.labelKirikTespitInfo = QtWidgets.QLabel(self.KirikTespitiInfoFrame)
        self.labelKirikTespitInfo.setGeometry(QtCore.QRect(33, 18, 391, 25))
        self.labelKirikTespitInfo.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color:    #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: medium;\n"
"    font-size: 20px;\n"
"}")
        self.labelKirikTespitInfo.setObjectName("labelKirikTespitInfo")
        self.CatlakTespitiFrame = QtWidgets.QFrame(self.centralwidget)
        self.CatlakTespitiFrame.setGeometry(QtCore.QRect(1385, 628, 505, 438))
        self.CatlakTespitiFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(6, 11, 38, 240),\n"
"        stop:1 rgba(26, 31, 55, 0)\n"
"    );\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.CatlakTespitiFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CatlakTespitiFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CatlakTespitiFrame.setObjectName("CatlakTespitiFrame")
        self.labelCatlakTespiti = QtWidgets.QLabel(self.CatlakTespitiFrame)
        self.labelCatlakTespiti.setGeometry(QtCore.QRect(34, 19, 461, 45))
        font = QtGui.QFont()
        font.setFamily("Plus-Jakarta-Sans")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelCatlakTespiti.setFont(font)
        self.labelCatlakTespiti.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: bold;\n"
"    font-size: 32px;\n"
"}")
        self.labelCatlakTespiti.setObjectName("labelCatlakTespiti")
        self.CatlakTespitInfoFrame = QtWidgets.QFrame(self.CatlakTespitiFrame)
        self.CatlakTespitInfoFrame.setGeometry(QtCore.QRect(31, 94, 443, 60))
        self.CatlakTespitInfoFrame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:1,\n"
"    stop:0 rgba(0, 0, 0, 255),\n"
"    stop:0.480769 rgba(9, 139, 7, 255),\n"
"    stop:1 rgba(9, 139, 7, 255)\n"
");\n"
"\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.CatlakTespitInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CatlakTespitInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CatlakTespitInfoFrame.setObjectName("CatlakTespitInfoFrame")
        self.labelCatlakTespitInfo = QtWidgets.QLabel(self.CatlakTespitInfoFrame)
        self.labelCatlakTespitInfo.setGeometry(QtCore.QRect(33, 18, 391, 25))
        self.labelCatlakTespitInfo.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color:    #F4F6FC;\n"
"    font-family: \'Plus-Jakarta-Sans\';\n"
"    font-weight: medium;\n"
"    font-size: 20px;\n"
"}")
        self.labelCatlakTespitInfo.setObjectName("labelCatlakTespitInfo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelSmart.setText(_translate("MainWindow", "SMART"))
        self.labelSaw.setText(_translate("MainWindow", "SAW"))
        self.btnControlPanel.setText(_translate("MainWindow", " Kontrol Paneli"))
        self.btnPositioning.setText(_translate("MainWindow", "Konumlandırma"))
        self.btnCamera.setText(_translate("MainWindow", "Kamera Verileri"))
        self.btnSensor.setText(_translate("MainWindow", "Sensör Verileri"))
        self.btnTracking.setText(_translate("MainWindow", "İzleme"))
        self.labelDate.setText(_translate("MainWindow", "14.12.2025 Çarşamba"))
        self.labelTime.setText(_translate("MainWindow", "12.30"))
        self.labelTespitEdilenKirik.setText(_translate("MainWindow", "Tespit Edilen Kırık Sayısı"))
        self.labelTespitEdilenKirikValue.setText(_translate("MainWindow", "12"))
        self.labelTespitEdilenDis.setText(_translate("MainWindow", "Tespit Edilen Diş Sayısı"))
        self.labelTespitEdilenDisValue.setText(_translate("MainWindow", "235"))
        self.labelTestereSagligi.setText(_translate("MainWindow", "Testere Sağlığı Yüzdesi"))
        self.labelTestereSagligiValue.setText(_translate("MainWindow", "16.35"))
        self.labelAsinmaYuzdesi.setText(_translate("MainWindow", "Aşınma Yüzdesi"))
        self.labelAsinmaYuzdesiValue.setText(_translate("MainWindow", "16.35"))
        self.labelTestereDurumu.setText(_translate("MainWindow", "Testere Durumu"))
        self.labelTestereDurumuValue.setText(_translate("MainWindow", "Sağlıklı"))
        self.labelTestereDegisim.setText(_translate("MainWindow", "Şerit Testerenin Son Değişim Tarihi"))
        self.labelKirikTespiti.setText(_translate("MainWindow", "Kırık Tespiti"))
        self.labelKirikTespitInfo.setText(_translate("MainWindow", "14.12.2025 tarihinde 16 kırık tespit edildi."))
        self.labelCatlakTespiti.setText(_translate("MainWindow", "Çatlak Tespiti"))
        self.labelCatlakTespitInfo.setText(_translate("MainWindow", "Çatlak tespit edilmedi."))
